import type { App } from '../types/app';
import type { GraphData } from '../types/graph';

export const appsData: App[] = [
  { id: '1', name: 'supertokens-golang', icon: '🟦' },
  { id: '2', name: 'supertokens-java', icon: '☕' },
  { id: '3', name: 'supertokens-python', icon: '🐍' },
  { id: '4', name: 'supertokens-ruby', icon: '💎' },
  { id: '5', name: 'supertokens-go', icon: '🔵' },
];

export const graphsData: Record<string, GraphData> = {
  '1': {
    nodes: [
      {
        id: 'node-1',
        type: 'service',
        position: { x: 300, y: 0 },
        data: {
          label: 'Application',
          icon: 'app',
          cpu: 0.5,
          memory: 1.0,
          disk: 20,
          region: 'us-east-1',
          cost: 0.12,
          status: 'healthy',
          provider: 'AWS',
          description: 'Main application server running Go microservices',
        },
      },
      {
        id: 'node-2',
        type: 'service',
        position: { x: 100, y: 250 },
        data: {
          label: 'MongoDB',
          icon: 'mongodb',
          cpu: 0.02,
          memory: 0.05,
          disk: 10,
          region: 'us-east-1',
          cost: 0.03,
          status: 'healthy',
          provider: 'AWS',
          description: 'Primary document database for user sessions',
        },
      },
      {
        id: 'node-3',
        type: 'service',
        position: { x: 500, y: 250 },
        data: {
          label: 'Redis',
          icon: 'redis',
          cpu: 0.01,
          memory: 0.25,
          disk: 5,
          region: 'us-east-1',
          cost: 0.02,
          status: 'degraded',
          provider: 'AWS',
          description: 'In-memory cache for session tokens',
        },
      },
      {
        id: 'node-4',
        type: 'service',
        position: { x: 100, y: 500 },
        data: {
          label: 'PostgreSQL',
          icon: 'postgresql',
          cpu: 0.04,
          memory: 0.1,
          disk: 50,
          region: 'us-east-1',
          cost: 0.05,
          status: 'healthy',
          provider: 'AWS',
          description: 'Relational database for core auth data',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true },
      { id: 'e1-3', source: 'node-1', target: 'node-3', animated: true },
      { id: 'e2-4', source: 'node-2', target: 'node-4' },
    ],
  },
  '2': {
    nodes: [
      {
        id: 'node-1',
        type: 'service',
        position: { x: 300, y: 0 },
        data: {
          label: 'Application',
          icon: 'app',
          cpu: 0.8,
          memory: 2.0,
          disk: 30,
          region: 'eu-west-1',
          cost: 0.18,
          status: 'healthy',
          provider: 'AWS',
          description: 'Java Spring Boot application server',
        },
      },
      {
        id: 'node-2',
        type: 'service',
        position: { x: 150, y: 250 },
        data: {
          label: 'PostgreSQL',
          icon: 'postgresql',
          cpu: 0.06,
          memory: 0.5,
          disk: 100,
          region: 'eu-west-1',
          cost: 0.08,
          status: 'healthy',
          provider: 'AWS',
          description: 'Primary relational database',
        },
      },
      {
        id: 'node-3',
        type: 'service',
        position: { x: 450, y: 250 },
        data: {
          label: 'Redis',
          icon: 'redis',
          cpu: 0.02,
          memory: 0.5,
          disk: 10,
          region: 'eu-west-1',
          cost: 0.04,
          status: 'healthy',
          provider: 'GCP',
          description: 'Distributed cache layer',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true },
      { id: 'e1-3', source: 'node-1', target: 'node-3', animated: true },
    ],
  },
  '3': {
    nodes: [
      {
        id: 'node-1',
        type: 'service',
        position: { x: 300, y: 0 },
        data: {
          label: 'Application',
          icon: 'app',
          cpu: 0.3,
          memory: 0.5,
          disk: 15,
          region: 'ap-south-1',
          cost: 0.09,
          status: 'healthy',
          provider: 'GCP',
          description: 'Python FastAPI service',
        },
      },
      {
        id: 'node-2',
        type: 'service',
        position: { x: 100, y: 250 },
        data: {
          label: 'MongoDB',
          icon: 'mongodb',
          cpu: 0.03,
          memory: 0.1,
          disk: 20,
          region: 'ap-south-1',
          cost: 0.04,
          status: 'down',
          provider: 'GCP',
          description: 'NoSQL document store',
        },
      },
      {
        id: 'node-3',
        type: 'service',
        position: { x: 500, y: 250 },
        data: {
          label: 'Redis',
          icon: 'redis',
          cpu: 0.01,
          memory: 0.12,
          disk: 5,
          region: 'ap-south-1',
          cost: 0.02,
          status: 'healthy',
          provider: 'GCP',
          description: 'Token caching layer',
        },
      },
      {
        id: 'node-4',
        type: 'service',
        position: { x: 300, y: 500 },
        data: {
          label: 'PostgreSQL',
          icon: 'postgresql',
          cpu: 0.05,
          memory: 0.2,
          disk: 40,
          region: 'ap-south-1',
          cost: 0.06,
          status: 'healthy',
          provider: 'Azure',
          description: 'Structured auth data store',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true },
      { id: 'e1-3', source: 'node-1', target: 'node-3', animated: true },
      { id: 'e2-4', source: 'node-2', target: 'node-4' },
      { id: 'e3-4', source: 'node-3', target: 'node-4' },
    ],
  },
  '4': {
    nodes: [
      {
        id: 'node-1',
        type: 'service',
        position: { x: 300, y: 0 },
        data: {
          label: 'Application',
          icon: 'app',
          cpu: 0.4,
          memory: 0.8,
          disk: 10,
          region: 'us-west-2',
          cost: 0.1,
          status: 'healthy',
          provider: 'Azure',
          description: 'Ruby on Rails application',
        },
      },
      {
        id: 'node-2',
        type: 'service',
        position: { x: 300, y: 250 },
        data: {
          label: 'PostgreSQL',
          icon: 'postgresql',
          cpu: 0.04,
          memory: 0.3,
          disk: 60,
          region: 'us-west-2',
          cost: 0.07,
          status: 'healthy',
          provider: 'Azure',
          description: 'Primary SQL database',
        },
      },
      {
        id: 'node-3',
        type: 'service',
        position: { x: 300, y: 500 },
        data: {
          label: 'Redis',
          icon: 'redis',
          cpu: 0.01,
          memory: 0.15,
          disk: 5,
          region: 'us-west-2',
          cost: 0.02,
          status: 'healthy',
          provider: 'Azure',
          description: 'Sidekiq job queue backend',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true },
      { id: 'e2-3', source: 'node-2', target: 'node-3' },
    ],
  },
  '5': {
    nodes: [
      {
        id: 'node-1',
        type: 'service',
        position: { x: 300, y: 0 },
        data: {
          label: 'Application',
          icon: 'app',
          cpu: 0.6,
          memory: 1.2,
          disk: 25,
          region: 'us-east-1',
          cost: 0.14,
          status: 'healthy',
          provider: 'AWS',
          description: 'Go gRPC microservice',
        },
      },
      {
        id: 'node-2',
        type: 'service',
        position: { x: 50, y: 250 },
        data: {
          label: 'MongoDB',
          icon: 'mongodb',
          cpu: 0.03,
          memory: 0.08,
          disk: 15,
          region: 'us-east-1',
          cost: 0.04,
          status: 'healthy',
          provider: 'AWS',
          description: 'Session storage database',
        },
      },
      {
        id: 'node-3',
        type: 'service',
        position: { x: 300, y: 250 },
        data: {
          label: 'Redis',
          icon: 'redis',
          cpu: 0.02,
          memory: 0.3,
          disk: 8,
          region: 'us-east-1',
          cost: 0.03,
          status: 'healthy',
          provider: 'AWS',
          description: 'Rate limiting cache',
        },
      },
      {
        id: 'node-4',
        type: 'service',
        position: { x: 550, y: 250 },
        data: {
          label: 'PostgreSQL',
          icon: 'postgresql',
          cpu: 0.05,
          memory: 0.4,
          disk: 80,
          region: 'us-east-1',
          cost: 0.06,
          status: 'degraded',
          provider: 'AWS',
          description: 'Core authentication data',
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'node-1', target: 'node-2', animated: true },
      { id: 'e1-3', source: 'node-1', target: 'node-3', animated: true },
      { id: 'e1-4', source: 'node-1', target: 'node-4', animated: true },
    ],
  },
};
